Set-Alias -Name "tc" -Value "Test-Connection"
Set-Alias -Name "g" -Value "git"
Set-Alias -Name "gs" -Value "git status"
Set-Alias -Name "ga" -Value "git add"
Set-Alias -Name "gco" -Value "git commit"
